### ISSUE TITLE
Conflict with Email Customizer

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/storefront#1161]
When trying to access the email customizer when using Storefront, a fatal error occurs.

AT test site:
![](https://cld.wthms.co/bQLHvE+)Image Link: https://cld.wthms.co/bQLHvE

Pressable test site displays a 404 in that area, and some hosts display the fatale error on that screen as well.

All sites display the same fatal error in log.

```
2019-06-10T21:55:01+00:00 CRITICAL Uncaught Error: Call to a member function value() on null in /wordpress/themes/storefront/2.5.0/inc/nux/class-storefront-nux-starter-content.php:1162
Stack trace:
#0 /wordpress/themes/storefront/2.5.0/inc/nux/class-storefront-nux-starter-content.php(1217): Storefront_NUX_Starter_Content->_get_created_starter_content_products()
#1 /wordpress/themes/storefront/2.5.0/inc/nux/class-storefront-nux-starter-content.php(1007): Storefront_NUX_Starter_Content->_query_starter_content('page', 'homepage', true)
#2 /wordpress/core/5.2.1/wp-includes/class-wp-hook.php(286): Storefront_NUX_Starter_Content->update_homepage_content(Object(WP_Customize_Manager))
#3 /wordpress/core/5.2.1/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/5.2.1/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /wordpress/core/5.2.1/wp-includes/class-wp-customize-manager.php(1887): do_action('customize_previ...', Object(WP_Customize_Manager))
#6 /wordpress/core/5.2.1/wp-includes/class-wp-customize-manager.php(937): WP_Customize_Manager->customize_preview_init()
#7 /wordpress/core/5.2.1/wp-includes/class-wp-hook.php(286): WP_Customize_Manager->wp_loaded('')
#8 /wordpress/core/5.2.1/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#9 /wordpress/core/5.2.1/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#10 /wordpress/core/5.2.1/wp-settings.php(546): do_action('wp_loaded')
#11 /srv/htdocs/wp-config.php(84): require_once('/wordpress/core...')
#12 /wordpress/core/5.2.1/wp-load.php(42): require_once('/srv/htdocs/wp-...')
#13 /wordpress/core/5.2.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#14 /wordpress/core/5.2.1/index.php(17): require('/wordpress/core...')
#15 {main}
  thrown in /wordpress/themes/storefront/2.5.0/inc/nux/class-storefront-nux-starter-content.php on line 1162
```

**Comment by tiagonoronha** [comment]
@melindahelt this has been fixed already, but we haven't made a new Storefront release yet.

Here's the relevant commit: https://github.com/woocommerce/storefront/commit/9e2a3a1ff03d673ead6d9c7707165e9bc930bc65.
